version: '3'

services:
  db:
    environment:
      POSTGRES_DB: fw
      POSTGRES_USER: fw_user
      POSTGRES_PASSWORD: fw_password
    image: postgres:10.1-alpine
    restart: always
    expose:
    - "5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command:
    - python /code/manage.py migrate --noinput
    - python /code/manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/code
    ports:
    - 8000:8000
    environment:
      SECRET_KEY: changemeinprod
      DATABASE_URL: postgres://fw_user:fw_password@db/fw
      DJANGO_MANAGEPY_MIGRATE: on
    depends_on:
    - db

volumes:
  postgres_data:
