# Generated by Django 2.1.3 on 2018-11-18 05:26

import django.contrib.postgres.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('comment_text', models.TextField(verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('name', models.TextField(verbose_name='Название события')),
                ('description', models.TextField(blank=True, verbose_name='Описание события')),
                ('event_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата события')),
                ('place_name', models.TextField(blank=True, verbose_name='Место проведения')),
                ('place_picture', models.TextField(blank=True, verbose_name='Фото места проведения')),
                ('comments', models.ManyToManyField(to='api.Comment', verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'событие',
                'verbose_name_plural': 'события',
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('name', models.TextField(verbose_name='Название доклада')),
                ('description', models.TextField(blank=True, verbose_name='Описание доклада')),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None, verbose_name='Фотографии доклада')),
                ('comments', models.ManyToManyField(to='api.Comment', verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'доклад',
                'verbose_name_plural': 'доклады',
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('name', models.TextField(verbose_name='Имя спикера')),
                ('photo', models.TextField(blank=True, verbose_name='Фото спикера')),
                ('description', models.TextField(blank=True, verbose_name='Описание спикера')),
                ('comments', models.ManyToManyField(to='api.Comment', verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'спикер',
                'verbose_name_plural': 'спикеры',
            },
        ),
        migrations.AddField(
            model_name='presentation',
            name='speakers',
            field=models.ManyToManyField(to='api.Speaker', verbose_name='Спикеры'),
        ),
        migrations.AddField(
            model_name='event',
            name='presentations',
            field=models.ManyToManyField(to='api.Presentation', verbose_name='Доклады'),
        ),
    ]
